### ISSUE TITLE
Error: name 'xrange' not defined

### ISSUE THREAD

**Issue by thomasdebeus** [stekhn/average-faces-opencv#3]
Now I've got the following error.

```
vrouw8.jpg
vrouw8.jpg.txt
vrouw9.jpg
vrouw9.jpg.txt
Traceback (most recent call last):
  File "average.py", line 302, in <module>
    main()
  File "average.py", line 66, in main
    for i in xrange(0, num_images):
NameError: name 'xrange' is not defined
```

**Comment by zufanka** [comment]
xrange is python 2.7 , in python 3.6 the method is called range()
